### ISSUE TITLE
Version 0.18.0 appears to have Increase the Shadow-CLJS version dependency

### ISSUE THREAD

**Issue by lostineverland** [eerohele/Tutkain#117]
Following the `0.18.0` upgrade I could no longer use version `2.18.0` of Shadow-CLJS. This should mentioned/added to the changelog and docs.

The failure was:
```sh
shadow-cljs - config: /Users/code/notes.03/shadow-cljs.edn
shadow-cljs - server version: 2.18.0 running at http://localhost:9630
shadow-cljs - nREPL server started on port 50428
shadow-cljs - watching build :app
[:app] Configuring build.
[:app] Compiling ...
[:app] Build completed. (165 files, 1 compiled, 0 warnings, 1.89s)
Exception in thread "async-thread-macro-13" clojure.lang.ExceptionInfo: No handler for message {:message {:runtime-id #object[clojure.lang.Atom 0x31eaeaac {:status :ready, :val 3}], :tag #object[clojure.lang.Atom 0x5dfa984b {:status :ready, :val :ret}], :ret-chan #object[clojure.core.async.impl.channels.ManyToManyChannel 0x3c318089 "clojure.core.async.impl.channels.ManyToManyChannel@3c318089"], :to-relay #object[clojure.core.async.impl.channels.ManyToManyChannel 0x4964880a "clojure.core.async.impl.channels.ManyToManyChannel@4964880a"], :from-relay #object[clojure.core.async.impl.channels.ManyToManyChannel 0x7f3eca83 "clojure.core.async.impl.channels.ManyToManyChannel@7f3eca83"], :op :unknown-op, :msg {:op :obj-edn, :oid "036011e9-65c9-4995-b681-6962effcb965", :from 5}, :from 3}}
        at tutkain.shadow$eval16354$fn__16355.invoke(shadow.clj:122)
        at clojure.lang.MultiFn.invoke(MultiFn.java:229)
        at tutkain.shadow$init$fn__16362.invoke(shadow.clj:146)
        at clojure.core.async$thread_call$fn__3181.invoke(async.clj:484)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

Version `2.23.2` works (or at the least it solved my issue). I should also add that I'm running on Clojure `1.10.3`

**Comment by eerohele** [comment]
Thank you for reporting the issue, and my sincere apologies for the breaking change! This is something neglected to account for.

>This should mentioned/added to the changelog and docs.

I agree; I'll update both when I get the chance. I'll also try to account for this in CI.

**Comment by lostineverland** [comment]
No worries, I appreciate your work!
