### ISSUE TITLE
Case sensitivity issue on install

### ISSUE THREAD

**Issue by slifin** [eerohele/tutkain#3]
Installed like so
<img width="1440" alt="Screenshot 2020-04-02 at 17 15 36" src="https://user-images.githubusercontent.com/198857/78272627-add62400-7505-11ea-95f8-7f60419b0655.png">
Console log output: 

```
reloading plugin tutkain.tutkain
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Packages/tutkain/tutkain.py", line 12, in <module>
    import Tutkain.brackets as brackets
ImportError: No module named 'Tutkain'
```
I got this working by capitalising the Tutkain folder from `tutkain` might be good in the docs to have a line that is `git clone <this repo> Tutkain` to make the capitalisation explicit

**Comment by slifin** [comment]
Ah just got to see it in action, I'm using:
`clj -J-Dclojure.server.jvm="{:port 5555 :accept clojure.core.server/io-prepl}"` 
<img width="718" alt="Screenshot 2020-04-02 at 17 32 50" src="https://user-images.githubusercontent.com/198857/78274360-00184480-7508-11ea-878e-74bd5444343b.png">
cool :D

**Comment by eerohele** [comment]
Thanks for the report and for giving it a try!

This is actually an error in the code — the imports should be in lower case. Fixed in https://github.com/eerohele/tutkain/commit/abfa8861a25e113c7c3f9c2dc310e61ba2ecfbd2.

Anyway, happy to hear you got it working! The next thing on my todo list is formatting exceptions such that they're a bit more readable.

**Comment by eerohele** [comment]
@slifin Just a heads up since you're probably the only person on the planet besides me who might be using this thing: the prepl route turned out to be, uh... untenable, so I've decided to switch over to nREPL. Apologies if this causes you trouble.

Let me know if I can help you with the transition over to nREPL if necessary, though.
